//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finel_project_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int messageID { get; set; }
        public int workerID { get; set; }
        public Nullable<bool> nonRead { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string message1 { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
