//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finel_project_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker_inbox
    {
        public int MessageID { get; set; }
        public int WorkerID { get; set; }
        public string Message { get; set; }
        public Nullable<bool> NonRead { get; set; }
    
        public virtual worker_inbox worker_inbox1 { get; set; }
        public virtual worker_inbox worker_inbox2 { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
